# Generated by Django 4.2.7 on 2023-11-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_Img', models.ImageField(upload_to='static/images/')),
                ('quantity', models.IntegerField(default=1)),
                ('item_Type', models.CharField(choices=[('FP', 'Finished Product'), ('MT', 'Material'), ('WIP', 'Work in progress')], default='MT', max_length=10)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_app.inventory')),
            ],
        ),
    ]
