# Generated by Django 4.2.7 on 2023-11-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
