# Generated by Django 4.2.7 on 2023-11-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemType',
            new_name='item_Type',
        ),
    ]
