# Generated by Django 4.2.7 on 2023-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0002_rename_itemtype_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_Img',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
